services:
  web:
    build: .
    image: server:latest
    ports:
      - "80:80"
    environment:
      - ENV=${ENV}
      - DB_HOST: db
      - DB_NAME: ${DB_DATABASE}
      - DB_USER: ${DB_USER}
      - DB_PASS: ${DB_PASSWORD}
    volumes:
      - ./public/:/var/www/localhost/htdocs
    depends_on:
      - db
    networks:
      - lamp-network

  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "8080:80"
    networks:
      - lamp-network
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER: ${DB_USER} 
      # PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db-data:

networks:
  lamp-network: 
    driver: bridge