services:
  web:
    image: server:latest
    ports:
      - "80:80"
    environment:
      - ENV=production
    volumes:
      - ./public/:/var/www/localhost/htdocs
    depends_on:
      - db
    networks:
      - lamp-network

  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "8080:80"
    networks:
      - lamp-network
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db-data:

networks:
  lamp-network: 
    driver: bridge